// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"es_CO": &dictionary{index: es_COIndex, data: es_COData},
	}
	fallback := language.MustParse("es-CO")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Agregar Tarea":                   9,
	"Contraseña":                      0,
	"Email":                           8,
	"Id no valido":                    3,
	"Iniciar Sesión":                  7,
	"Nombre no puede estar vacío":     2,
	"Status no valido":                4,
	"Tarea Agregada exitosamente.":    1,
	"Tarea actualizada exitosamente.": 5,
	"Tareas completadas: %d":          11,
	"Tareas totales: %d":              10,
	"Welcome!\n":                      6,
}

var en_USIndex = []uint32{ // 13 elements
	0x00000000, 0x00000009, 0x00000022, 0x00000037,
	0x00000042, 0x00000051, 0x0000006c, 0x0000007a,
	0x00000081, 0x00000087, 0x00000090, 0x000000a3,
	0x000000ba,
} // Size: 76 bytes

const en_USData string = "" + // Size: 186 bytes
	"\x02Password\x02Task added successfully.\x02Name cannot be empty\x02Inva" +
	"lid Id\x02Invalid Status\x02Task updated successfully.\x04\x00\x01\x0a" +
	"\x09\x02Welcome!\x02Log in\x02Email\x02Add task\x02Total tasks: %[1]d" +
	"\x02Completed tasks: %[1]d"

var es_COIndex = []uint32{ // 13 elements
	0x00000000, 0x0000000c, 0x00000029, 0x00000046,
	0x00000053, 0x00000064, 0x00000084, 0x00000095,
	0x000000a5, 0x000000ab, 0x000000b9, 0x000000cf,
	0x000000e9,
} // Size: 76 bytes

const es_COData string = "" + // Size: 233 bytes
	"\x02Contraseña\x02Tarea Agregada exitosamente.\x02Nombre no puede estar " +
	"vacío\x02Id no valido\x02Status no valido\x02Tarea actualizada exitosame" +
	"nte.\x04\x00\x01\x0a\x0c\x02Bienvenido!\x02Iniciar Sesión\x02Email\x02Ag" +
	"regar Tarea\x02Tareas totales: %[1]d\x02Tareas completadas: %[1]d"

	// Total table size 571 bytes (0KiB); checksum: 88B5687D
